lavalink:
  server:
    sources:
      youtube: false
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.1"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: false
    clients:
      - WEB

logging:
  file:
    path: ./lavalink-logs/

  level:
    root: INFO
    lavalink: INFO
