services:
  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx8G
      - SERVER_PORT=${WAVELINK_PORT}
      - LAVALINK_SERVER_PASSWORD=${WAVELINK_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - ${WAVELINK_PORT}:${WAVELINK_PORT}

  sky_whale:
    build: .
    volumes:
      - ./log:/sky_whale/log
      - ./.env:/sky_whale/.env
      - ./sky_whale.db:/sky_whale/sky_whale.db
